name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug }}
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug }}
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: "[debug] Print when triggered from main"
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: echo "This workflow was triggered from the main branch"
      - name: Greeting
        run: |
          echo "Hello, ${{ github.actor }}!"
          echo "This workflow is running on the ${{ runner.os }} operating system."
