name: 09 - Using Functions
on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing Step
        run: |
          echo "This step will fail"
          exit 1
      - name: I will be skipped
        if: ${{ success()}}
        run: echo "I will print if the previous step passes"
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails"
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will print if the workflow is not cancelled"
      - name: I will execute
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow is cancelled"
